// Données fictives pour le mode démo

export const DEMO_USER = {
  id: 'demo-user-1',
  email: 'demo@app.com',
}

export const DEMO_PROFILE = {
  id: 'demo-user-1',
  couple_name: 'Alex & Sam',
  bio: 'Couple curieux et bienveillant, nous cherchons des rencontres conviviales sans prise de tête.',
  avatar_url: null,
  orientation: 'hetero_hetero',
  looking_for: ['couple', 'woman'],
  seeking: ['rencontres_occasionnelles', 'amis_libertins'],
  availabilities: ['weekend', 'rdv'],
  limits: ['discretion', 'preservatif'],
  max_distance_km: 50,
  visibility: 'public',
  status: 'active',
  hide_location: false,
  email_1: 'demo@app.com',
  email_1_confirmed: true,
  email_2: null,
  email_2_confirmed: false,
  distance_km: 0,
}

export const DEMO_PROFILES = [
  {
    id: 'demo-2',
    couple_name: 'Marc & Julie',
    bio: 'Couple hétéro de 35 ans, ouverts et discrets. Nous cherchons des amis libertins pour des soirées sympa.',
    avatar_url: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600&q=80',
    orientation: 'hetero_hetero',
    looking_for: ['couple'],
    seeking: ['echangisme', 'amis_libertins'],
    limits: ['discretion', 'pas_photo'],
    distance_km: 8,
    lng: 3.88, lat: 43.61,
  },
  {
    id: 'demo-3',
    couple_name: 'Tom & Léa',
    bio: 'Bisexuels tous les deux, on aime rencontrer des gens ouverts d\'esprit. Préférence pour les couples.',
    avatar_url: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=600&q=80',
    orientation: 'bi_all',
    looking_for: ['couple', 'woman'],
    seeking: ['decouverte', 'rencontres_occasionnelles'],
    limits: ['preservatif', 'discretion'],
    distance_km: 14,
    lng: 3.87, lat: 43.62,
  },
  {
    id: 'demo-4',
    couple_name: 'Pierre & Marie',
    bio: 'Couple expérimenté, 40 ans, cherchons des rencontres de qualité dans la bonne humeur.',
    avatar_url: 'https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=600&q=80',
    orientation: 'hetero_bi',
    looking_for: ['couple'],
    seeking: ['echangisme', 'rencontres_occasionnelles'],
    limits: ['preservatif', 'pas_contact_hors_site'],
    distance_km: 23,
    lng: 3.90, lat: 43.59,
  },
  {
    id: 'demo-5',
    couple_name: 'Chris & Jordan',
    bio: 'Nouveaux dans le milieu, curieux et respectueux. On prend notre temps.',
    avatar_url: 'https://images.unsplash.com/photo-1521305916504-4a1121188589?w=600&q=80',
    orientation: 'bi_all',
    looking_for: ['couple', 'woman', 'man'],
    seeking: ['decouverte'],
    limits: ['pas_photo', 'discretion'],
    distance_km: 31,
    lng: 3.85, lat: 43.64,
  },
  {
    id: 'demo-6',
    couple_name: 'Nico & Lisa',
    bio: 'Couple actif qui aime les soirées festives. Ouverts et sans tabous.',
    avatar_url: 'https://images.unsplash.com/photo-1464692805480-a69dfaafdb0d?w=600&q=80',
    orientation: 'hetero_hetero',
    looking_for: ['couple'],
    seeking: ['echangisme', 'amis_libertins', 'rencontres_occasionnelles'],
    limits: ['preservatif'],
    distance_km: 45,
    lng: 3.92, lat: 43.57,
  },
]

export const DEMO_MATCHES = [
  {
    id: 'match-1',
    couple_a: 'demo-user-1',
    couple_b: 'demo-2',
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    profile: DEMO_PROFILES[0],
    lastMessage: 'Avec plaisir ! On vous propose samedi soir ?',
  },
  {
    id: 'match-2',
    couple_a: 'demo-user-1',
    couple_b: 'demo-3',
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    profile: DEMO_PROFILES[1],
    lastMessage: null,
  },
]

export const DEMO_MESSAGES = {
  'match-1': [
    {
      id: 'msg-1',
      match_id: 'match-1',
      sender_id: 'demo-2',
      content: 'Bonjour ! Votre profil nous a beaucoup plu 😊',
      photo_url: null,
      read_at: new Date().toISOString(),
      deleted_for: [],
      created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000 + 1000).toISOString(),
    },
    {
      id: 'msg-2',
      match_id: 'match-1',
      sender_id: 'demo-user-1',
      content: 'Bonjour Marc & Julie ! Pareil de notre côté, on est ravis du match 🙂',
      photo_url: null,
      read_at: new Date().toISOString(),
      deleted_for: [],
      created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000 + 2000).toISOString(),
    },
    {
      id: 'msg-3',
      match_id: 'match-1',
      sender_id: 'demo-2',
      content: 'On serait dispo pour se rencontrer prochainement, vous êtes libres quand ?',
      photo_url: null,
      read_at: new Date().toISOString(),
      deleted_for: [],
      created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    },
    {
      id: 'msg-4',
      match_id: 'match-1',
      sender_id: 'demo-user-1',
      content: 'Avec plaisir ! On vous propose samedi soir ?',
      photo_url: null,
      read_at: new Date().toISOString(),
      deleted_for: [],
      created_at: new Date(Date.now() - 3600 * 1000).toISOString(),
    },
  ],
  'match-2': [],
}
