import { normaliser } from './motCache.js'

/**
 * Le vocabulaire des jeux.
 *
 * Liste maison plutot qu'un dictionnaire importe : les listes francaises
 * ouvertes sont sous MPL ou GPL, ce qui creerait des obligations sur un
 * projet commercial. Et un vocabulaire choisi vaut mieux qu'un
 * dictionnaire exhaustif, ou trainent des mots que personne ne joue.
 *
 * Les mots sont ranges sans accent ni trait d'union, en capitales : c'est
 * la forme sur laquelle normaliser() compare. « ECORCE » couvre donc
 * « ecorce » comme « Ecorce ».
 *
 * Limite assumee : un mot francais valide absent d'ici sera refuse. On
 * prefere le dire au joueur ("mot non reconnu") plutot que de pretendre
 * qu'il s'est trompe. La liste est faite pour grandir.
 */

const LISTE = `
ABRI AILE AIME AINE AIRE ALLE AMER AMIE ANGE ANSE AOUT ARBRE ARCHE ARDU ARME
ATRE AUBE AUNE AUTRE AVEU AVIS AXES BAIE BAIN BALE BANC BARBE BASE BATON
BEAU BEC BELLE BERGE BETE BIAIS BIEN BIERE BILAN BILLE BLANC BLEU BOIRE BOIS
BOITE BOND BORD BOUE BOUT BRAS BREF BRIN BRISE BRUIT BRUME BUEE BULLE BUREAU
CABANE CADRE CAFE CAGE CAISSE CALME CANAL CANNE CAPE CARRE CARTE CASE CAUSE
CAVE CEDRE CEINTURE CELA CENDRE CENT CERCLE CERF CESSE CHAIR CHAISE CHAMP
CHANT CHAOS CHARME CHASSE CHAT CHAUD CHEF CHEMIN CHENE CHER CHEVAL CHIEN
CHOIX CHOSE CHUTE CIBLE CIEL CIME CINQ CIRE CITE CLAIR CLASSE CLE CLOCHE
CLOU COEUR COIN COL COLLE COLERE COMBLE CONTE CORDE CORPS COTE COU COUCHE
COUDE COULEUR COUP COUR COURBE COURT COUSIN COUTEAU CRAIE CRAN CRETE CREUX
CRI CRIME CRISE CROIX CUBE CUIR CUISSE CUIVRE CYCLE DAME DANSE DATE DEBUT
DECOR DEDANS DEHORS DELAI DEMAIN DENT DEPART DESSIN DETTE DEUIL DEUX DIGUE
DIRE DISQUE DIVIN DOIGT DOMAINE DON DOS DOUCE DOUTE DOUX DRAP DROIT DUNE
DUREE EAU EBENE ECART ECHO ECLAT ECOLE ECORCE ECRAN ECRIN ECRIT ECUME EFFET
EGAL EGLISE ELAN ELEVE ELLE EMAIL EMOI ENCRE ENFANT ENFIN ENJEU ENNUI ENTRE
ENVIE EPAULE EPEE EPI EPOQUE EPOUX ERE ERREUR ESPACE ESPOIR ESSAI ETAGE ETAIN
ETANG ETAPE ETAT ETE ETOILE ETRE EVEIL EXACT EXCES EXIL FACE FADE FAIM FAIRE
FAIT FALAISE FAMILLE FANE FARD FAUTE FAUX FAVEUR FEE FER FERME FETE FEU
FEUILLE FIBRE FIEL FIER FIEVRE FIGURE FIL FILET FILLE FIN FLAMME FLANC FLEUR
FLOT FOI FOIN FOIRE FOIS FOND FORCE FORET FORME FORT FOSSE FOU FOULE FOYER
FRAIS FRANC FREIN FRERE FROID FRONT FRUIT FUITE FUMEE FUSIL GAIN GALET GANT
GARDE GARE GAUCHE GEANT GEL GENOU GENRE GESTE GLACE GLOIRE GORGE GOUT GOUTTE
GRACE GRAIN GRAND GRAS GRAVE GRIS GROS GROTTE GUERRE GUIDE HABIT HAIE HAINE
HALTE HASARD HAUT HERBE HEURE HIVER HOMME HONTE HORS HOTE HUILE HUIT HUMBLE
IDEE ILE IMAGE INDEX ISSUE IVOIRE IVRE JADIS JAMAIS JAMBE JARDIN JAUNE JETON
JEU JEUNE JOIE JOLI JOUE JOUR JUGE JUIN JUPE JURY JUSTE LAC LAINE LAIT LAME
LAMPE LANGUE LARGE LARME LEGER LENT LETTRE LEVRE LIBRE LIEN LIERRE LIEU LIGNE
LIMITE LINGE LION LIRE LISTE LIT LIVRE LOI LOIN LONG LOUP LOURD LUEUR LUMIERE
LUNE LUTTE LUXE MAIN MAIS MAISON MAITRE MAL MANCHE MANQUE MARBRE MARCHE MARE
MAREE MARGE MARIN MASQUE MASSE MAT MATIN MER MERE MERLE MESURE METAL METRE
MIDI MIEL MIEUX MILIEU MILLE MINCE MINE MINUIT MIROIR MODE MOINE MOINS MOIS
MOITIE MONDE MONNAIE MONT MORT MOT MOUCHE MOULIN MOUSSE MOYEN MUET MUR MURMURE
MUSIQUE MYSTERE NAGE NAIF NAPPE NEIGE NERF NEUF NEZ NID NIVEAU NOIR NOM NOMBRE
NORD NOTE NOUVEAU NOYAU NUAGE NUIT NUL NUQUE OCEAN ODEUR OEIL OEUF OEUVRE
OISEAU OMBRE ONDE ONGLE ONZE OPERA OR ORAGE ORANGE ORDRE OREILLE ORGUE ORME
OS OSER OUBLI OUEST OURS OUTIL OUVERT PAGE PAILLE PAIN PAIR PAIX PALAIS PALE
PANIER PAPIER PAR PARC PARDON PAROI PAROLE PART PARTIE PAS PASSE PATIENCE
PATTE PAUME PAUSE PAUVRE PAVE PAYS PEAU PECHE PEINE PENTE PERE PERLE PERTE
PESER PETIT PEU PEUPLE PEUR PHARE PHASE PHRASE PIANO PIECE PIED PIERRE PILE
PIN PIPE PISTE PLACE PLAGE PLAIE PLAINE PLAN PLANCHE PLANTE PLAT PLEIN PLI
PLOMB PLUIE PLUME PLUS POCHE POELE POEME POETE POIDS POIL POINT POIRE POIS
POISSON POITRINE POLE POMME PONT PORT PORTE POSTE POT POUCE POULE POUR POUSSE
POUVOIR PRAIRIE PRE PRES PRIERE PRIME PRINCE PRISE PRIX PROIE PROPRE PRUNE
PUCE PUIS PUITS PUR QUAI QUAND QUART QUATRE QUEUE QUI QUINZE RACE RACINE RADIO
RAIE RAISIN RAME RANG RARE RAT RAYON RECIT REFUGE REGARD REGLE REGNE REINE
RELIEF REMEDE RENARD RENDRE RENTREE REPAS REPOS RESTE REVE REVERS RICHE RIDE
RIEN RIRE RIVE RIVIERE ROBE ROC ROCHE ROI ROLE ROMAN RONCE ROND ROSE ROSEE
ROUE ROUGE ROUTE RUCHE RUE RUINE RUISSEAU RUMEUR RYTHME SABLE SAC SAGE SAISON
SALE SALLE SANG SANS SAULE SAUT SAVEUR SAVOIR SCENE SEAU SEC SECOURS SEIN
SEIZE SEL SEMAINE SENS SENTIER SEPT SERRE SEUIL SEUL SEVE SIECLE SIEGE SIGNE
SILENCE SILLON SIMPLE SITE SIX SOEUR SOIE SOIF SOIN SOIR SOL SOLEIL SOMBRE
SOMME SON SONGE SORT SORTIE SOUCI SOUFFLE SOUPE SOURCE SOURD SOURIRE SOUS
SOUVENIR SPHERE SPORT STADE STYLE SUC SUCRE SUD SUITE SUJET SUR SURFACE TABLE
TACHE TAILLE TAIRE TALON TANDIS TANT TAPIS TARD TASSE TAUX TEINTE TEL TEMPETE
TEMPS TENDRE TENIR TENTE TERME TERRE TETE TEXTE THE THEME TIEDE TIGE TIMBRE
TIRER TISSU TITRE TOILE TOIT TOMBE TON TONNERRE TORT TOUCHE TOUJOURS TOUR
TOUT TRACE TRAIN TRAIT TRAME TRAVAIL TREIZE TRESOR TRIBU TRISTE TROIS TROP
TROU TROUPE TRUC TUILE TUNNEL TYPE UN USAGE USINE UTILE VAGUE VAIN VALEUR
VALLEE VAPEUR VASE VASTE VEAU VEILLE VEINE VELO VENIR VENT VENTRE VER VERBE
VERGER VERRE VERS VERT VERTU VESTE VETU VEUF VIDE VIE VIEUX VIF VIGNE VILLAGE
VILLE VIN VINGT VIOLET VIRAGE VISAGE VISITE VITE VITRE VIVRE VOEU VOIE VOILE
VOIR VOISIN VOIX VOL VOLET VOLUME VOTRE VOUTE VOYAGE VRAI VUE ZONE
`

/** Toutes les formes acceptees, en capitales sans accent. */
export const MOTS = new Set(
  LISTE.split(/\s+/).map(m => m.trim()).filter(Boolean)
)

/** Le mot est-il reconnu ? Les accents et la casse n'ont pas d'importance. */
export function estUnMot(mot) {
  const m = normaliser(mot)
  return m.length > 0 && MOTS.has(m)
}

/** Les mots d'une longueur donnee, tries — sert aux tirages et aux grilles. */
export function motsDeLongueur(n) {
  return [...MOTS].filter(m => m.length === n).sort()
}

/**
 * Le mot peut-il s'ecrire avec les lettres proposees ?
 * Chaque lettre du tirage ne sert qu'une fois.
 */
export function estFormable(mot, lettres) {
  const restantes = {}
  for (const l of normaliser(lettres.join ? lettres.join('') : lettres)) {
    restantes[l] = (restantes[l] || 0) + 1
  }
  for (const l of normaliser(mot)) {
    if (!restantes[l]) return false
    restantes[l] -= 1
  }
  return true
}

/**
 * Les solutions du mot cache.
 *
 * Un sous-ensemble choisi parmi les mots de cinq lettres : on veut des
 * mots qu'on a plaisir a trouver, pas les plus frequents. Ils sont
 * ecrits avec leurs accents pour l'affichage — la comparaison, elle,
 * passe par normaliser().
 */
export const SOLUTIONS = [
  'Seuil', 'Marée', 'Écume', 'Lueur', 'Brume', 'Voile', 'Plume', 'Orage',
  'Neige', 'Cendre', 'Sillon', 'Écorce', 'Rosée', 'Ronce', 'Songe', 'Rivage',
  'Falaise', 'Fièvre', 'Murmure', 'Verger', 'Étoile', 'Silence', 'Tiède',
  'Aube', 'Écrin', 'Éclat', 'Ivoire', 'Vitre', 'Cible', 'Digue', 'Émoi',
  'Fable', 'Havre', 'Litre', 'Nappe', 'Ombre', 'Perle', 'Ruche', 'Saule',
  'Tache', 'Trame', 'Ancre', 'Barbe', 'Câble', 'Dune', 'Étain', 'Givre',
].filter(m => MOTS.has(normaliser(m)))

/** La solution d'un jour, tiree de facon reproductible. */
export function solutionDuJour(suivant) {
  return SOLUTIONS[Math.floor(suivant() * SOLUTIONS.length)]
}
